"""Strategy base module for CryptoQuant platform.

Defines the abstract base class for all trading strategies, signal types,
and the context object for strategy execution.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from enum import Enum, auto
from typing import Any, Dict, List, Optional

import structlog

from data.models import OHLCVCandle, OrderBook, Ticker


logger = structlog.get_logger(__name__)


class SignalType(Enum):
    """Trading signal types.

    Attributes:
        LONG: Enter long position
        SHORT: Enter short position
        CLOSE_LONG: Close existing long position
        CLOSE_SHORT: Close existing short position
        HOLD: No action, maintain current position
    """
    LONG = auto()
    SHORT = auto()
    CLOSE_LONG = auto()
    CLOSE_SHORT = auto()
    HOLD = auto()


@dataclass(frozen=True)
class Signal:
    """Trading signal generated by a strategy.

    Attributes:
        signal_type: Type of trading signal
        pair: Trading pair symbol (e.g., "BTC/USDT")
        timestamp: Unix timestamp in milliseconds when signal was generated
        price: Reference price for the signal
        confidence: Signal confidence score (0.0 to 1.0)
        metadata: Additional signal metadata (e.g., indicators, reasons)
    """
    signal_type: SignalType
    pair: str
    timestamp: int
    price: Decimal
    confidence: Decimal = Decimal('0.5')
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def datetime(self) -> datetime:
        """Convert timestamp to datetime object."""
        return datetime.fromtimestamp(self.timestamp / 1000)

    def is_entry(self) -> bool:
        """Check if signal is an entry signal."""
        return self.signal_type in (SignalType.LONG, SignalType.SHORT)

    def is_exit(self) -> bool:
        """Check if signal is an exit signal."""
        return self.signal_type in (SignalType.CLOSE_LONG, SignalType.CLOSE_SHORT)

    def is_hold(self) -> bool:
        """Check if signal is a hold signal."""
        return self.signal_type == SignalType.HOLD


@dataclass
class Position:
    """Current position state.

    Attributes:
        pair: Trading pair symbol
        side: Position side ("long" or "short")
        size: Position size
        entry_price: Average entry price
        entry_time: Unix timestamp when position was opened
        unrealized_pnl: Current unrealized P&L
    """
    pair: str
    side: str  # "long" or "short"
    size: Decimal
    entry_price: Decimal
    entry_time: int
    unrealized_pnl: Decimal = Decimal('0')

    @property
    def is_long(self) -> bool:
        """Check if position is long."""
        return self.side == "long"

    @property
    def is_short(self) -> bool:
        """Check if position is short."""
        return self.side == "short"

    @property
    def is_flat(self) -> bool:
        """Check if position is flat (no position)."""
        return self.size == 0


@dataclass
class StrategyContext:
    """Context object passed to strategies during execution.

    Provides access to current market data, account state, and historical data
    needed for strategy decision-making.

    Attributes:
        pair: Trading pair symbol
        timeframe: Candle timeframe (e.g., "1h", "15m")
        current_price: Current market price
        positions: Dict of open positions by pair
        balances: Account balance information
        candles: Recent OHLCV candles for calculations
        ticker: Latest ticker data
        order_book: Latest order book snapshot
        current_time: Current Unix timestamp in milliseconds
        params: Strategy-specific parameters
    """
    pair: str
    timeframe: str
    current_price: Decimal
    positions: Dict[str, Position] = field(default_factory=dict)
    balances: Dict[str, Decimal] = field(default_factory=dict)
    candles: List[OHLCVCandle] = field(default_factory=list)
    ticker: Optional[Ticker] = None
    order_book: Optional[OrderBook] = None
    current_time: int = 0
    params: Dict[str, Any] = field(default_factory=dict)

    def get_position(self, pair: Optional[str] = None) -> Optional[Position]:
        """Get position for specified pair or default pair.

        Args:
            pair: Trading pair symbol (defaults to context pair)

        Returns:
            Position object if exists, None otherwise
        """
        target = pair or self.pair
        return self.positions.get(target)

    def has_position(self, pair: Optional[str] = None) -> bool:
        """Check if there is an open position for the pair.

        Args:
            pair: Trading pair symbol (defaults to context pair)

        Returns:
            True if position exists and is not flat
        """
        pos = self.get_position(pair)
        return pos is not None and not pos.is_flat

    def get_balance(self, currency: str) -> Decimal:
        """Get balance for specific currency.

        Args:
            currency: Currency code (e.g., "BTC", "USDT")

        Returns:
            Available balance or 0 if not found
        """
        return self.balances.get(currency, Decimal('0'))

    def get_recent_candles(self, n: int) -> List[OHLCVCandle]:
        """Get the most recent n candles.

        Args:
            n: Number of candles to retrieve

        Returns:
            List of recent candles (up to n)
        """
        return self.candles[-n:] if len(self.candles) >= n else self.candles


class StrategyBase(ABC):
    """Abstract base class for all trading strategies.

    All strategies must inherit from this class and implement the required
    methods. The strategy lifecycle is:
        1. initialize() - Called once at startup
        2. on_bar() - Called for each new candle/bar
        3. generate_signal() - Called to get trading signal

    Attributes:
        name: Strategy identifier name
        params: Strategy configuration parameters
        logger: Structured logger instance
    """

    def __init__(self, name: str, params: Optional[Dict[str, Any]] = None) -> None:
        """Initialize strategy.

        Args:
            name: Strategy identifier name
            params: Strategy configuration parameters
        """
        self.name = name
        self.params = params or {}
        self.logger = structlog.get_logger(__name__).bind(strategy=name)
        self._initialized = False

    @abstractmethod
    def initialize(self) -> None:
        """Initialize strategy state.

        Called once before the strategy starts processing data.
        Override to set up indicators, pre-calculate values, etc.
        """
        pass

    @abstractmethod
    def generate_signal(self, context: StrategyContext) -> Signal:
        """Generate trading signal based on current context.

        This is the core method that analyzes market data and returns
        a trading signal (LONG, SHORT, CLOSE, or HOLD).

        Args:
            context: Current market and account context

        Returns:
            Signal object with signal type and metadata
        """
        pass

    def on_bar(self, candle: OHLCVCandle, context: StrategyContext) -> Signal:
        """Process new candle/bar data.

        Called for each new candle. Updates internal state and generates
        a signal. Override if you need custom bar processing logic.

        Args:
            candle: New OHLCV candle data
            context: Current market and account context

        Returns:
            Signal object from generate_signal
        """
        if not self._initialized:
            self.initialize()
            self._initialized = True

        self.logger.debug(
            "Processing bar",
            pair=candle.pair,
            timestamp=candle.timestamp,
            close=candle.close_price,
        )

        return self.generate_signal(context)

    def on_tick(self, ticker: Ticker, context: StrategyContext) -> Optional[Signal]:
        """Process tick data (optional).

        Called for each tick update if running in tick mode.
        Default implementation returns None (no signal on tick).
        Override for tick-based strategies.

        Args:
            ticker: Latest ticker data
            context: Current market and account context

        Returns:
            Signal object or None
        """
        return None

    def get_param(self, key: str, default: Any = None) -> Any:
        """Get parameter value with default.

        Args:
            key: Parameter name
            default: Default value if not found

        Returns:
            Parameter value or default
        """
        return self.params.get(key, default)

    def set_param(self, key: str, value: Any) -> None:
        """Set parameter value.

        Args:
            key: Parameter name
            value: Parameter value
        """
        self.params[key] = value

    def reset(self) -> None:
        """Reset strategy state.

        Clears internal state for fresh start. Override if you have
        state that needs cleanup.
        """
        self._initialized = False

    def validate_params(self) -> List[str]:
        """Validate strategy parameters.

        Returns list of validation error messages. Empty list means valid.
        Override to add custom parameter validation.

        Returns:
            List of error messages
        """
        return []

    def __repr__(self) -> str:
        """String representation of strategy."""
        return f"{self.__class__.__name__}(name='{self.name}', params={self.params})"
